plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'ru.magzook'
version = '0.0.1'
description = 'Sellers and transactions REST service'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // db
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'

    // web
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    // swagger ui
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'

    // validation
    implementation 'org.springframework.boot:spring-boot-starter-validation:4.0.6'

    // test
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'com.h2database:h2'
}

tasks.named('test') {
    useJUnitPlatform()
}