spring.application.name=sellers-rest-service

# db
spring.datasource.url=jdbc:postgresql://localhost:5432/sellers_db
spring.datasource.username=admin
spring.datasource.password=12345678

# hibernate
spring.jpa.hibernate.ddl-auto=validate